### ISSUE TITLE
`/metatx` API should deduplicate call requests

### ISSUE THREAD

**Issue by zomglings** [moonstream-to/api#870]
Currently, the `/metatx` API has no deduplication logic for call requests, which means a user could load the same call request into the API multiple times, each time creating a new row in the corresponding relation.

We need to add deduplication logic here, conditional on the type of call request being created.

If a duplicate request is sent in a batch, the non-duplicated requests should still be registered successfully.

This is the flavor of idempotence this endpoint will offer.

**Comment by zomglings** [comment]
For `raw` requests, this should be a unique constraint in DB on the `"calldata"` field of the specification.

For `dropper-v0.2.0` requests, this should be a unique constraint in DB on the `"requestID"` field of the specification.

When we insert data into `call_requests`, we should use `INSERT ... ON CONFLICT DO UPDATE`.

**Comment by zomglings** [comment]
In SQLAlchemy, you can create a partial unique index like this: https://stackoverflow.com/questions/27976683/creating-partial-unique-index-with-sqlalchemy-on-postgres

We are using these in Brood: https://github.com/bugout-dev/brood/blob/56d7edf31d4245a0ad527fdfb00f3dd09f9f18c8/brood/models.py#L123

There may be other solutions, perhaps `CheckConstraint` as used in `brood`: https://github.com/bugout-dev/brood/blob/56d7edf31d4245a0ad527fdfb00f3dd09f9f18c8/brood/models.py#L163

**Comment by kompotkot** [comment]
- [ ] Reorg db PR https://github.com/moonstream-to/api/pull/882
- [ ] Add constraint
