### ISSUE TITLE
Add leaderboard metadata

### ISSUE THREAD

**Issue by oolumorin** [moonstream-to/api#953]
Users should be able to specify when creating a leaderboard:

1. The column names for player and score.
2. What blockchain(s) the leaderboard is associated with, if any.
3. If associated with an EVM chain, what the network configuration for that chain should be (to add to Metamask) only if the chain isn’t supported by Moonstream.
4. Whether they want to display the Metamask component.

**Comment by Andrei-Dolgolev** [comment]
PR
https://github.com/moonstream-to/api/pull/968

**Comment by Andrei-Dolgolev** [comment]
resolve https://github.com/moonstream-to/api/pull/968

**Comment by oolumorin** [comment]
Think through address normalization
